name: Test actions workflow
on: [push]
jobs:
  print-test:
    name: Test of echo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Heihei"


  linter:
    uses: github/super-linter@v4
    env:
      VALIDATE_ALL_CODEBASE: false
      DEFAULT_BRANCH: master
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

