name: Test actions workflow
on: [push]
jobs:
  print-test:
    name: Test of echo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Heihei"

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
#        todo: use github/super-linter when will be resolved https://github.com/github/super-linter/issues/708
        uses: Neha-Sinha2305/super-linter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

