name: Testing of actions
on: [push]
jobs:
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"


  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
#        todo: use github/super-linter when will be resolved https://github.com/github/super-linter/issues/708
        uses: Neha-Sinha2305/super-linter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
